### ISSUE TITLE
Turn Off TV broken in latest dev PR

### ISSUE THREAD

**Issue by starkillerOG** [bendavid/aiopylgtv#10]
@bendavid I just tested the code of your latest open PR: https://github.com/home-assistant/home-assistant/pull/31099

I noticed that the turn_off service does not work anymore using the code of that PR.
I have an 'older' webos2 TV: LG EG920V

Could you maybe have a look at it?

**Comment by starkillerOG** [comment]
Moreover that PR did fix the state updating proporly again (it was indeed  broken for me in the dev version before that latest PR)

**Comment by bendavid** [comment]
Should be fixed consistently by https://github.com/bendavid/aiopylgtv/commit/55b689cebe40f27a57a996e8bdf24976b35ffd88
(the corresponding home assistant PR has been updated as well)

**Comment by starkillerOG** [comment]
@bendavid Thanks!
