### ISSUE TITLE
InsertText endpoint

### ISSUE THREAD

**Issue by dundylion** [bendavid/aiopylgtv#20]
Hi.
I've wiresharked some new endpoint that can be usefull
It looks like:
com.webos.service.ime/insertText
payload have attributes text (string) and replace (boolean)

We can fill any text forms with that.
And it's faster than pressing every button on screen keyboard

**Comment by chros73** [comment]
Which model did you try it with? I have LG Oled B8.

**Comment by dundylion** [comment]
> Which model did you try it with? I have LG Oled B8.

I have LG UH610V
