### ISSUE TITLE
power_off turns the tv on

### ISSUE THREAD

**Issue by basnijholt** [bendavid/aiopylgtv#6]
I noticed this in Home Assistant.

There should be an additional check, that the code doesn't execute if the TV is off.

**Comment by bendavid** [comment]
This is patched around in home assistant by https://github.com/home-assistant/home-assistant/pull/30998 but I will add a more proper fix here together with some other improvements.

**Comment by bendavid** [comment]
Fixed by https://github.com/bendavid/aiopylgtv/commit/c56be398f1d6fa06feac5c519b783ee075742ad7
